spring:
    application:
        name: SpringPracticeRESTMVC
    threads:
        virtual:
            enabled: true
    jpa:
        show-sql: true
    #        to generate database schema automatically, uncomment the properties bellow
    #        properties:
    #            jakarta:
    #                persistence:
    #                    schema-generation:
    #                        scripts:
    #                            action: drop-and-create
    #                            create-source: metadata
    #                            drop-target: drop-and-create.sql
    #                            create-target: drop-and-create.sql
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
    flyway:
        enabled: false
    security:
        user:
            password: password
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9000

bootstrap:
    csv-file-path: classpath:csvdata/beers.csv

server:
    port: 9090

# enable 'localdb' profile in application.properties
# or in run configuration for intellij idea ultimate
#   1. disable non integration tests
#   2. use @ActiveProfiles("localdb") in integration test classes

logging:
    level:
        com:
            example: debug
#        org:
#            springframework:
#                security: trace