spring:
    jpa:
        database: mysql
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true

    datasource:
        username: restadmin
        password: password
        url: jdbc:mariadb://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace