spring:
    application:
        name: SpringPracticeRESTMVC
    jpa:
        show-sql: true
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
#    profiles:
#        active: jpa

logging:
    level:
        com:
            example: debug