spring:
    application:
        name: SpringPracticeRESTMVC
    jpa:
        show-sql: true
    properties:
        hibernate:
            format-sql: true
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb

logging:
    level:
        com:
            example: debug