spring:
    jpa:
        database: mysql
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    flyway:
        enabled: true

    datasource:
        username: ${MYSQL_USER:restadmin}
        password: ${MYSQL_PASS:password}
        url: jdbc:mysql://${DB_HOST_ADDRESS:localhost}:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        hikari:
            pool-name: RestDB-Pool
            maximum-pool-size: 5
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                useLocalSessionState: true
                rewriteBatchStatements: true
                cacheServerConfiguration: true
                cacheResultSetMetadata: true
                elideSetAutoCommits: true
                maintainTimeStats: false

bootstrap:
    csv-file-path: classpath:csvdata/beers.csv

logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace



# 1. Command for docker container creation and running
#       docker run --name spring-practice-restmvc -d -e DB_HOST_ADDRESS=host.docker.internal -p 8081:8081 spring-practice-restmvc:0.0.1-SNAPSHOT --spring.profiles.active=localdb

# 2. Set and link (spring-practice-restmvc) with the jwt-issuer-host container
#       docker run --name spring-practice-restmvc -d -e DB_HOST_ADDRESS=host.docker.internal -e SERVER_PORT=8080 -p 8081:8080 --link spring-practice-auth-server:spring-practice-auth-server -e SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://spring-practice-auth-server:9000 spring-practice-restmvc:0.0.1-SNAPSHOT --spring.profiles.active=localdb