spring:
    jpa:
        database: mysql
    datasource:
        username: restadmin
        password: password
        url: jdbc:mariadb://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
