spring:
    application:
        name: SpringPracticeRESTMVC
    jpa:
        show-sql: true
#        to generate database schema automatically, uncomment the properties bellow
#        properties:
#            jakarta:
#                persistence:
#                    schema-generation:
#                        scripts:
#                            action: drop-and-create
#                            create-source: metadata
#                            drop-target: drop-and-create.sql
#                            create-target: drop-and-create.sql
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
    profiles:
        active: localdb

logging:
    level:
        com:
            example: debug