spring:
    jpa:
        database: mysql
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true

    datasource:
        username: restadmin
        password: password
        url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        hikari:
            pool-name: RestDB-Pool
            maximum-pool-size: 5
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                useLocalSessionState: true
                rewriteBatchStatements: true
                cacheServerConfiguration: true
                cacheResultSetMetadata: true
                elideSetAutoCommits: true
                maintainTimeStats: false

logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace